version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: query-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: query_service
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../../server/query/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - app-network
    restart: unless-stopped

  nacos:
    image: nacos/nacos-server:v2.0.3 # 使用特定版本而不是latest
    container_name: nacos
    ports:
      - "8848:8848" # 主端口
      - "9848:9848" # 客户端grpc端口  
      - "9849:9849" # 服务端grpc端口
    environment:
      MODE: standalone
      NACOS_AUTH_ENABLE: true
      NACOS_AUTH_TOKEN: 8JNJZz9vQc6uT6V0aG1rL2V4YW1wbGUvb3V0cHV0L3NlY3JldC50eHQ=
      NACOS_AUTH_IDENTITY_KEY: nacos
      NACOS_AUTH_IDENTITY_VALUE: nacos
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

  query-service:
    image: query-service-arm:latest
    container_name: query-service-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/query_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8080
      GRPC_SERVER_PORT: 9090
      # 使用 Nacos 配置
      DUBBO_REGISTRY_ADDRESS: nacos://nacos:8848?username=nacos&password=nacos
    ports:
      - "8080:8080" # HTTP 端口 (容器内8080映射到主机8080)
      - "9090:9090" # gRPC 端口
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_started
    networks:
      - app-network
    restart: unless-stopped

  home-service:
    image: home-service-arm:latest
    container_name: home-service
    ports:
      - "8888:8888" # HTTP 端口 (容器内8888映射到主机8888)
    environment:
      - SERVER_PORT=8888
      - QUERY_CLIENT_HTTP_BASE_URL=http://query-service-app:8080
      - QUERY_CLIENT_GRPC_HOST=query-service-app
      - QUERY_CLIENT_GRPC_PORT=9090
      - DUBBO_REGISTRY_ADDRESS=nacos://nacos:8848?username=nacos&password=nacos
    depends_on:
      query-service:
        condition: service_started
      nacos:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
