apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-service
  namespace: kt-connect-test
  labels:
    app: home-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-service
  template:
    metadata:
      labels:
        app: home-service
    spec:
      containers:
      - name: home-service
        image: 11.54.85.220:84/worsun/home-service
        ports:
        - containerPort: 8888
          name: http
        env:
        - name: SERVER_PORT
          value: "8888"
        - name: QUERY_CLIENT_HTTP_BASE_URL
          value: "http://query-service:8080"
        - name: QUERY_CLIENT_GRPC_HOST
          value: "query-service"
        - name: QUERY_CLIENT_GRPC_PORT
          value: "9090"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: home-service
  namespace: kt-connect-test
spec:
  selector:
    app: home-service
  ports:
  - name: http
    port: 8888
    targetPort: 8888
  type: ClusterIP