spring:
  datasource:
    url: jdbc:mysql://mysql:3306/query_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: ${SERVER_PORT:8080}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9090}

dubbo:
  application:
    name: query-service
    qos-enable: false  # 禁用QoS，避免端口冲突
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: nacos://nacos:8848?username=nacos&password=nacos
    simplified: true
  scan:
    base-packages: com.worsun.spring_demo.query.service