spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/query_service}
    username: ${SPRING_DATASOURCE_USERNAME:your_username}
    password: ${SPRING_DATASOURCE_PASSWORD:your_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: ${SERVER_PORT:8080}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9090}